- name: "Get an IAM token"
  uri:
    method: POST
    url: "{{ansible_env.IBMCLOUD_IAM_API_ENDPOINT | default ('https://iam.cloud.ibm.com')}}/identity/token"
    body_format: json
    body: "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey={{ ansible_env.IC_API_KEY }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: iam_resp

- name: "Set IAM_TOKEN"
  set_fact:
    IAM_TOKEN: "{{ iam_resp['json']['access_token'] }}"

- debug:
    var: IAM_TOKEN

- include: create.yml
  when: mode == "create"

- include: destroy.yml
  when: mode == "destroy" and destroy_vpn is true