---
- name: Destroy IBM Cloud VPC VSI
  hosts: localhost
  collections:
   - ibm.cloudcollection
  environment:
    IC_REGION: "{{ region }}"
  tasks:

    - name: Release Floating IP
      ibm_is_floating_ip:
        state: absent
        id: "{{ fip.id }}"
      when: fip is defined

    - name: Remove VSI
      ibm_is_instance:
        state: absent
        id: "{{ vsi.id }}"
        vpc: "{{ vpc.id }}"
        profile: "{{ vsi_profile }}"
        image: "{{ (image_dict|dict2items|selectattr('key', 'match', vsi_image)|list|first).value }}"
        keys:
          - "{{ ssh_key.id }}"
        primary_network_interface:
          - subnet: "{{ subnet_dict[zone] }}"
        zone: "{{ zone }}"
      when: vsi is defined

    # - name: Remove SSH Key
    #   ibm_is_ssh_key:
    #     state: absent
    #     id: "{{ ssh_key.id }}"
    #   when: ssh_key is defined

    # - name: Remove VPC Subnets
    #   ibm_is_subnet:
    #     state: absent
    #     id: "{{ item.value }}"
    #   loop: "{{ subnet_dict|dict2items }}"
    #   when: subnet_dict is defined

    # - name: Remove VPC
    #   ibm_is_vpc:
    #     state: absent
    #     id: "{{ vpc.id }}"
    #   when: vpc is defined
