
---
# Name for the VPC
vpc_name: zlinux-ansible

# Name for the components for the VPC created objects (VPC, subnetwork, VSI)
zlinux-ansible:
  subnet: "{{ vpc_name }}-{{ zone }}"
  vsi: "{{ vpc_name }}-vsi"
  fip: "{{ vpc_name }}-fip"

# Regular expresion for the VSI image name
# If multiple matches are found the first one is taken
vsi_image: ".*ubuntu-18-04.*s390x.*"

# Profile name for the VSI
vsi_profile: bz2-2x8

# Name of the uploaded key
# Please notice that the same key might not be uploaded twice
# under different names
ssh_key_name: 'angel-rsa'
ssh_public_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"

# Size of the created subnetwork
total_ipv4_address_count: 256

# Region to deploy to
region: "jp-tok"
#region: "eu-gb"

#Zone within the region
zone: "{{region}}-1"

# If cache_vsi=True then VSI creation will only be attemped if not cached
#cache_vsi: True
cache_vsi: False
